CREATE TABLE IF NOT EXISTS inscripciones (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    alumno_nombre VARCHAR(150) NOT NULL,
    dni VARCHAR(30) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    nivel VARCHAR(40) NOT NULL,
    anio VARCHAR(20) NULL,
    orientacion VARCHAR(40) NULL,
    resp1_nombre VARCHAR(150) NOT NULL,
    resp1_dni VARCHAR(30) NOT NULL,
    resp1_telefono VARCHAR(40) NOT NULL,
    resp1_email VARCHAR(190) NULL,
    resp2_nombre VARCHAR(150) NULL,
    resp2_dni VARCHAR(30) NULL,
    resp2_telefono VARCHAR(40) NULL,
    resp2_email VARCHAR(190) NULL,
    observaciones TEXT NULL,
    boletin_path VARCHAR(255) NOT NULL,
    ciclo_lectivo YEAR NOT NULL DEFAULT 2027,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_dni_ciclo (dni, ciclo_lectivo),
    INDEX idx_inscripciones_ciclo (ciclo_lectivo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
